name: Towns Build

on:
  push:
    branches: [ main, dev ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Erlaubt das manuelle Starten des Workflows

jobs:
  build:
    name: Compile and Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            natives: natives-windows
            zip_name: Towns-Windows.zip
          - os: ubuntu-latest
            natives: natives-linux
            zip_name: Towns-Linux.zip
          - os: macos-latest
            natives: natives-macos-arm64
            zip_name: Towns-MacOS.zip

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 26
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '26'
          cache: 'maven'

      - name: Build with Maven (App Image)
        shell: bash
        run: mvn -B package -Pdist -Dlwjgl.natives=${{ matrix.natives }} --file pom.xml

      - name: Package compiled files
        shell: bash
        run: |
          cd target/dist
          zip -r ../../${{ matrix.zip_name }} Towns*

      - name: Publish Pre-Release (Main)
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: latest
          name: Latest Development Build
          files: ${{ matrix.zip_name }}
          prerelease: true

      - name: Publish Release (Tags)
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.zip_name }}
          generate_release_notes: true
